"use strict";
(function(){
const hash=s=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0};
const rng=seed=>()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/4294967296);
const pick=(r,a)=>a[Math.floor(r()*a.length)];
const shuffle=(r,a)=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const mc=(q,answer,distractors,explain,kind="begrip")=>({q,answer,options:shuffle(rng(hash(q+answer)),[answer,...distractors.filter(x=>x!==answer).slice(0,3)]),explain,kind});

const PROFILE_META={
 dani:{name:"Dani",age:8,grade:"midden groep 5 · rekenen eind groep 5",icon:"⚽",subtitle:"Sterke spits, uitvinder en missieheld",accent:"#46d6bd",subjects:["reading","spelling","math"],subjectLabels:{reading:"Begrijpend lezen",spelling:"Spelling",math:"Rekenen"},subjectIcons:{reading:"📖",spelling:"✍️",math:"🧮"},daily:["reading","spelling","math","reading","spelling"],free:["reading","spelling","math","logic","english","world","focus"],tags:["Voetbal","Kracht","Avontuur","Uitvinden"]},
 zana:{name:"Zana",age:11,grade:"groep 8 · plus · brugklas HAVO/VWO",icon:"🏑",subtitle:"Toekomstige CEO, wereldstudent en hockeystrateeg",accent:"#a87cff",subjects:["reading","language","math","english","world","science","critical"],subjectLabels:{reading:"Begrijpend lezen",language:"Taal & spelling",math:"Rekenen",english:"Engels",world:"Wereldoriëntatie",science:"Wetenschap",critical:"Kritisch denken"},subjectIcons:{reading:"📚",language:"🖋️",math:"📊",english:"🇬🇧",world:"🌍",science:"🔬",critical:"🧠"},daily:["reading","math","language","reading","english","critical"],free:["reading","language","math","english","world","science","critical","finance","focus"],tags:["Hockey","Leiderschap","Engels","Uitdaging"]},
 lena:{name:"Lena",age:5,grade:"groep 2",icon:"🌈",subtitle:"Nieuwsgierige ontdekker en beginnende hockeyheld",accent:"#ff8bb6",subjects:["story","letters","counting","shapes"],subjectLabels:{story:"Luisterverhaal",letters:"Letters & klanken",counting:"Tellen",shapes:"Vormen & patronen"},subjectIcons:{story:"📕",letters:"🔤",counting:"🔢",shapes:"🧩"},daily:["story","letters","counting","shapes"],free:["story","letters","counting","shapes","memory","focus"],tags:["Hockey","Dieren","Kleuren","Ontdekken"]}
};

const ACTIVITY_META={
 reading:{icon:"📖",title:"Verhalenkluis",desc:"Een nieuw verhaal met inhoudelijke vragen"},story:{icon:"📕",title:"Luister & kijk",desc:"Kort verhaal met duidelijke vragen"},spelling:{icon:"✍️",title:"Spellingarena",desc:"12 heldere zinnen en woordvragen"},language:{icon:"🖋️",title:"Taalstudio",desc:"12 taal-, spelling- en redactievraagstukken"},math:{icon:"🧮",title:"Rekenrace 20",desc:"20 gevarieerde sommen met timer"},letters:{icon:"🔤",title:"Letterfeest",desc:"Klanken, beginletters en rijm"},counting:{icon:"🔢",title:"Telavontuur",desc:"Tellen, vergelijken en kleine sommen"},shapes:{icon:"🧩",title:"Patroonpret",desc:"Vormen, kleuren en logische reeksen"},english:{icon:"🇬🇧",title:"English Quest",desc:"Woordenschat, grammatica en tekst"},world:{icon:"🌍",title:"Wereldlab",desc:"Aardrijkskunde, geschiedenis en maatschappij"},science:{icon:"🔬",title:"Science Lab",desc:"Onderzoeken, verklaren en redeneren"},critical:{icon:"🧠",title:"Denk als een onderzoeker",desc:"Bronnen, argumenten en logica"},finance:{icon:"💼",title:"Junior CEO",desc:"Geld, plannen, winst en keuzes"},logic:{icon:"🧩",title:"Breinbrekers",desc:"Logica, reeksen en ruimtelijk denken"},memory:{icon:"🃏",title:"Memory",desc:"Zoek dezelfde plaatjes"},focus:{icon:"👾",title:"Focus Arcade",desc:"Klik, rem af en reageer slim"}
};

const daniThemes=[
 {title:"de finale onder de lichtmasten",place:"een stadion aan de rand van de stad",goal:"de finale van een internationaal jeugdtoernooi winnen",problem:"de tegenstander steeds met twee verdedigers op hem doordekte",clue:"de rechtsback telkens te vroeg naar binnen stapte",plan:"eerst uit de spits wegzakken en daarna buitenom diepgaan",result:"een beslissende assist en later het winnende doelpunt",word:["compact","dapper"]},
 {title:"het geheim van de verdwenen beker",place:"het clubhuis na een bloedstollende wedstrijd",goal:"de kampioensbeker terugvinden vóór de huldiging",problem:"de beker spoorloos was en iedereen door elkaar begon te praten",clue:"er glimmende modderspetters richting het oude materiaalhok liepen",plan:"de aanwijzingen rustig in volgorde zetten",result:"de beker achter een stapel pionnen werd gevonden",word:["aanwijzing","onrust"]},
 {title:"de Afleidings-Alien in de dug-out",place:"een uitwedstrijd tegen de koploper",goal:"het tactische plan van de coach precies uitvoeren",problem:"een denkbeeldige alien hem aan auto’s, haaien en chips liet denken",clue:"zijn focusknop hem hielp drie kernwoorden te onthouden",plan:"stoppen, ademen en de eerstvolgende actie hardop noemen",result:"hij op het juiste moment vrijliep en scoorde",word:["concentratie","beslissend"]},
 {title:"het voetbalveld op Mars",place:"een trainingsbasis op Mars in het jaar 2048",goal:"de eerste interplanetaire voetbalwedstrijd spelen",problem:"de lage zwaartekracht elke sprong veel hoger maakte",clue:"een zachte pass langer bleef zweven dan een harde lage pass",plan:"korter passen en eerder naar de landingsplek bewegen",result:"Nederland de Mars Cup won",word:["zwaartekracht","voorspellen"]},
 {title:"de haai bij het trainingskamp",place:"een zonnig eiland waar het team op trainingskamp was",goal:"een conditietraining langs de kust voltooien",problem:"een grote donkere vin vlak bij de boeien opdook",clue:"de vin regelmatig verdween en twee kleine vinnen ernaast verschenen",plan:"de badmeester waarschuwen en op veilige afstand observeren",result:"het een groep vriendelijke dolfijnen bleek te zijn",word:["observeren","voorzichtig"]},
 {title:"de uitvinding die Oranje sneller maakte",place:"het innovatiecentrum van de KNVB",goal:"een hulpmiddel ontwerpen dat spelers beter laat kijken",problem:"vermoeide spelers alleen nog naar de bal keken",clue:"een korte trilling genoeg was om spelers aan hun omgeving te herinneren",plan:"een eenvoudige polsband bouwen die geen antwoorden voorspelde",result:"het team sneller vrije ruimte herkende",word:["innovatie","waarnemen"]},
 {title:"de karatekeeper",place:"een sportkamp met voetbal en karate",goal:"een penaltytoernooi winnen zonder wild te schieten",problem:"de keeper met snelle karatebewegingen iedereen afleidde",clue:"de keeper vlak vóór het schot altijd één schouder liet zakken",plan:"lang wachten, rustig kijken en laag naar de andere hoek schieten",result:"Dani drie strafschoppen achter elkaar scoorde",word:["beheersing","misleiden"]},
 {title:"het kasteeltoernooi",place:"een oud kasteel met een voetbalveld op de binnenplaats",goal:"de Gouden Ridderbal veroveren",problem:"de bal steeds in een smalle gracht naast het veld belandde",clue:"een lage pass over het midden veel veiliger was",plan:"minder hard en nauwkeuriger samenspelen",result:"het team zonder balverlies de finale won",word:["nauwkeurig","strategie"]},
 {title:"de race tegen de Lamborghini",place:"een afgesloten testbaan naast een voetbalacademie",goal:"een sportauto laten stoppen met een zelfbedachte veiligheidssensor",problem:"de sensor alleen reageerde wanneer het object recht voor de auto stond",clue:"voetballers juist schuin en onverwacht bewegen",plan:"drie sensoren in een waaier plaatsen",result:"de auto ruim op tijd remde en Dani’s ontwerp een prijs won",word:["sensor","prototype"]},
 {title:"de dinosaurus achter het doel",place:"een avonturenpark waar een jeugdtoernooi werd gehouden",goal:"de kwartfinale afmaken ondanks vreemde geluiden",problem:"achter het doel een enorme mechanische dinosaurus plotseling begon te brullen",clue:"het brullen telkens precies na een fluitsignaal startte",plan:"het geluid als vast startsein gebruiken in plaats van ervan te schrikken",result:"Dani juist sneller reageerde en twee keer scoorde",word:["mechanisch","reageren"]},
 {title:"de sneeuwfinale",place:"een bergdorp waar onverwacht sneeuw viel",goal:"de laatste wedstrijd van het wintertoernooi spelen",problem:"de bal op het gladde veld doorschoof",clue:"zachte passes en kleine passen meer controle gaven",plan:"het tempo verlagen en als team dichter bij elkaar spelen",result:"een slimme combinatie het winnende doelpunt opleverde",word:["controle","aanpassen"]},
 {title:"de nacht in het verlaten stadion",place:"een oud stadion tijdens een stroomstoring",goal:"Lena’s verloren hockeytasje terugvinden",problem:"in de donkere gangen vreemde schaduwen bewogen",clue:"de schaduwen steeds gelijk met de noodlamp draaiden",plan:"met Zana een route tekenen en per vak zoeken",result:"het tasje bij de spelerstunnel lag en de ‘monsters’ vlaggen bleken",word:["schaduw","systematisch"]}
];
const daniSide=["Zana","Lena","papa Jonathan","moeder Lana","zijn beste teamgenoot","coach Sam"];
const daniWeather=["frisse ochtendlucht","warme zon","dreigende wolken","harde wind","lichte regen","heldere sterrenhemel"];
const daniTwists=["Toen leek alles plotseling mis te gaan","Net op het moment dat Dani wilde versnellen","Vlak voor de belangrijkste actie","Iedereen keek naar Dani, maar hij keek juist om zich heen","De eerste oplossing werkte niet","Een onverwacht geluid veranderde de situatie"];

function daniStory(seed,level=3){
 const r=rng(hash("dani"+seed)),t=pick(r,daniThemes),side=pick(r,daniSide),weather=pick(r,daniWeather),twist=pick(r,daniTwists),focus=pick(r,["kijken, denken, doen","stoppen, ademen, kiezen","bal, ruimte, team","rust, richting, actie"]);
 const storyCode=hash(seed).toString(36).toUpperCase();
 const title=`Dani en ${t.title}`;
 const paras=[
 `De ${weather} hing boven ${t.place}. Op het digitale bord stond missiecode ${storyCode}. Dani trok zijn veters stevig aan. Vandaag wilde hij ${t.goal}. Hij voelde zich sterk, want hij had goed getraind en wist dat inzet vaak belangrijker is dan meteen alles perfect kunnen. ${side} gaf hem een boks en zei dat hij vooral goed moest blijven kijken.`,
 `Al snel ontstond er een probleem: ${t.problem}. Dani merkte dat zijn hoofd sneller wilde handelen dan verstandig was. Even dacht hij aan een glimmende sportauto die langs de lijn stond, aan een enge film en zelfs aan de vraag hoeveel pannenkoeken er in een voetbaltas zouden passen. Hij grinnikte. De Afleidings-Alien was weer langsgekomen.`,
 `${twist}. Dani drukte zijn duim tegen zijn wijsvinger, zijn geheime focusknop. Hij zei in zichzelf: “${focus}.” Daarna bekeek hij de situatie opnieuw. Toen zag hij dat ${t.clue}. Dat was geen toeval, maar een aanwijzing.`,
 `Dani overlegde kort met ${side}. Samen besloten ze ${t.plan}. De eerste poging lukte nog niet helemaal. In plaats van boos te worden, vroeg Dani zich af wat er precies misging. Hij veranderde één klein onderdeel van het plan en probeerde het opnieuw.`,
 `Nu werkte het wel. ${t.result}. Dani juichte, maar hij wist dat het succes niet alleen door kracht kwam. Hij had zijn aandacht teruggehaald, een patroon ontdekt en samengewerkt. Dat voelde bijna net zo goed als zelf het mooiste doelpunt maken.`,
 `Later thuis vertelde hij aan Lana en Jonathan wat er was gebeurd. Lena maakte er meteen een wild verhaal van waarin een haai, een dinosaurus en een keeper samen in een Lamborghini wegreden. Zana lachte. Dani schreef in zijn uitvindersboek: “Een doorzetter probeert niet blind hetzelfde. Hij kijkt wat er gebeurt en past zijn plan aan.”`
 ];
 const qs=[
  mc("Waar speelt het belangrijkste deel van het verhaal zich af?",t.place,daniThemes.filter(x=>x.place!==t.place).slice(0,3).map(x=>x.place),"De plaats wordt direct in de eerste alinea genoemd.","letterlijk"),
  mc("Wat was het belangrijkste probleem?",t.problem,daniThemes.filter(x=>x.problem!==t.problem).slice(0,3).map(x=>x.problem),"Dit probleem zorgt ervoor dat Dani zijn aanpak moet veranderen.","letterlijk"),
  mc("Welke aanwijzing hielp Dani verder?",t.clue,daniThemes.filter(x=>x.clue!==t.clue).slice(0,3).map(x=>x.clue),"Dani keek opnieuw en ontdekte dit patroon.","verband"),
  mc("Welke eigenschap laat Dani vooral zien?","Hij blijft rustig onderzoeken en past zijn plan aan.",["Hij wacht tot iemand anders alles oplost.","Hij gebruikt alleen zijn spierkracht.","Hij doet steeds precies hetzelfde zonder te kijken."],"Doorzetten betekent hier: leren van wat er gebeurt en gericht opnieuw proberen.","afleiden"),
  mc("Wat is de hoofdgedachte?","Goed kijken, samenwerken en bijsturen helpt bij een moeilijk probleem.",["De sterkste speler moet altijd zelf scoren.","Afleiding kan nooit worden gestopt.","Een wedstrijd is alleen leuk wanneer alles meteen lukt."],"Deze boodschap komt terug in het probleem, het plan en de afloop.","hoofdgedachte"),
  mc(`Wat betekent “${t.word[0]}” in deze tekst het best?`,vocabMeaning(t.word[0]),vocabDistractors(t.word[0]),`De betekenis past bij de manier waarop het woord in het verhaal wordt gebruikt.`,"woordenschat")
 ];
 return{title,story:paras.join("\n\n"),questions:qs,level,genre:"voetbalavontuur",estimatedWords:paras.join(" ").split(/\s+/).length,seed};
}
function vocabMeaning(w){const d={compact:"dicht bij elkaar",dapper:"moedig",aanwijzing:"iets dat helpt om een oplossing te vinden",onrust:"een toestand waarin mensen niet kalm zijn",concentratie:"je aandacht bij één ding houden",beslissend:"heel belangrijk voor de afloop",zwaartekracht:"de kracht die dingen naar een planeet trekt",voorspellen:"vooraf bedenken wat waarschijnlijk gebeurt",observeren:"aandachtig bekijken",voorzichtig:"met aandacht voor gevaar",innovatie:"een nieuwe nuttige uitvinding of aanpak",waarnemen:"met je zintuigen opmerken",beheersing:"jezelf rustig kunnen sturen",misleiden:"iemand iets anders laten denken",nauwkeurig:"heel precies",strategie:"een doordacht plan",sensor:"onderdeel dat iets in de omgeving meet",prototype:"eerste proefmodel",mechanisch:"werkend met een machine",reageren:"iets doen als antwoord op wat gebeurt",controle:"de situatie kunnen sturen",aanpassen:"veranderen zodat iets beter past",schaduw:"donkere vorm doordat licht wordt tegengehouden",systematisch:"volgens een vaste, slimme volgorde"};return d[w]||"precies passend bij de situatie"}
function vocabDistractors(w){return shuffle(rng(hash(w)),["zo hard mogelijk bewegen","zonder nadenken beginnen","iets dat alleen in een droom bestaat","een toevallig geluid"]);}

const zanaDomains=[
 {domain:"duurzame campus",setting:"een internationale universiteit in Londen",issue:"of een oud gebouw moest worden gerenoveerd of vervangen door een energiepositieve nieuwbouw",data:"renovatie veroorzaakte nu 38 procent minder uitstoot, terwijl nieuwbouw na zeventien jaar netto gunstiger werd",stake:"studenten, omwonenden en het universiteitsbestuur",bias:"de bouwer alleen de besparing na twintig jaar benadrukte",decision:"een combinatie van renovatie en één kleiner nieuw gebouw",concept:"tijdshorizon"},
 {domain:"hockeydata",setting:"een Europees jeugdtoernooi in Antwerpen",issue:"of spelers op basis van statistieken of observaties geselecteerd moesten worden",data:"de speler met de meeste balcontacten leverde niet de meeste gevaarlijke aanvallen op",stake:"trainers, speelsters en data-analisten",bias:"de meetmethode acties zonder bal nauwelijks registreerde",decision:"data te combineren met video en gesprekken",concept:"meetbaarheid"},
 {domain:"start-up en privacy",setting:"een jongerencongres in Amsterdam",issue:"of een studie-app aandacht mocht meten via camera en microfoon",data:"de proefgroep gemiddeld twaalf procent langer doorwerkte, maar een derde zich bekeken voelde",stake:"leerlingen, ouders, scholen en de ontwikkelaar",bias:"de ontwikkelaar alleen succesvolle gebruikers in advertenties liet zien",decision:"alleen lokale meting zonder beelden op te slaan en altijd met toestemming",concept:"proportionaliteit"},
 {domain:"medisch onderzoek",setting:"een universitair ziekenhuis in Oxford",issue:"of een veelbelovende behandeling versneld beschikbaar moest komen",data:"een kleine studie verbetering liet zien, maar zeldzame bijwerkingen nog onvoldoende kon uitsluiten",stake:"patiënten, artsen, onderzoekers en toezichthouders",bias:"een patiëntenvereniging de mogelijke winst zwaarder woog dan de onzekerheid",decision:"beperkte toegang binnen een streng vervolgonderzoek",concept:"onzekerheid"},
 {domain:"maatschappelijke media",setting:"een redactielokaal in New York",issue:"of een spectaculair filmpje direct gepubliceerd kon worden",data:"het filmpje miljoenen keren was gedeeld, maar tijd, locatie en maker niet waren bevestigd",stake:"kijkers, betrokken personen en journalisten",bias:"populariteit ten onrechte als bewijs van betrouwbaarheid werd gebruikt",decision:"publicatie uit te stellen en eerst twee onafhankelijke bronnen te zoeken",concept:"bronverificatie"},
 {domain:"internationaal studeren",setting:"een scholenbeurs met universiteiten uit de Verenigde Staten en het Verenigd Koninkrijk",issue:"welke opleiding het best paste bij ambitie, kosten en welzijn",data:"de duurste opleiding het sterkste netwerk bood, maar ook de hoogste schuld en grootste afstand tot familie",stake:"Zana, haar gezin en toekomstige studiegenoten",bias:"ranglijsten vooral onderzoeksreputatie maten en minder het dagelijkse onderwijs",decision:"criteria te wegen en meerdere studenten persoonlijk te spreken",concept:"afwegingskader"},
 {domain:"bedrijfsovername",setting:"een fictieve sportkledingonderneming",issue:"of snelle groei door een overname verstandig was",data:"de omzet kon verdubbelen, terwijl de schuld verdrievoudigde en twee bedrijfsculturen sterk verschilden",stake:"medewerkers, klanten, aandeelhouders en leveranciers",bias:"de verkoper alleen optimistische synergieën presenteerde",decision:"een kleinere samenwerking te testen voordat een volledige overname werd gedaan",concept:"risicobeheersing"},
 {domain:"klimaatadaptatie",setting:"een kuststad in Kroatië",issue:"hoe de stad zich tegen hitte en wateroverlast moest beschermen",data:"bomen verkoeling gaven maar jaren nodig hadden, terwijl technische koeling snel werkte maar veel energie gebruikte",stake:"bewoners, toeristen, ondernemers en de gemeente",bias:"elk voorstel vooral zijn eigen meetbare voordeel liet zien",decision:"schaduw, groen, wateropvang en gerichte techniek te combineren",concept:"systeembenadering"},
 {domain:"kunstmatige intelligentie",setting:"een debat op een middelbare school",issue:"of AI een eerste versie van werkstukken mocht schrijven",data:"leerlingen sneller begonnen, maar soms fouten overnamen zonder controle",stake:"leerlingen, docenten, ouders en softwaremakers",bias:"voorstanders tijdwinst telden en tegenstanders vooral de slechtste voorbeelden gebruikten",decision:"AI alleen als denkpartner toe te staan met broncontrole en een reflectie op eigen keuzes",concept:"verantwoordelijkheid"},
 {domain:"topsport en welzijn",setting:"een nationale hockeyacademie",issue:"of extra trainingsuren altijd tot betere prestaties leiden",data:"techniek eerst verbeterde, maar slaaptekort daarna reactietijd en motivatie verslechterde",stake:"sporters, coaches, ouders en medische staf",bias:"selectiemomenten korte prestaties zwaarder lieten wegen dan duurzame ontwikkeling",decision:"trainingsbelasting individueel te plannen en herstel mee te meten",concept:"duurzame prestatie"},
 {domain:"democratisch bestuur",setting:"een jongerenraad in Den Haag",issue:"hoe scholieren invloed konden krijgen op gemeentelijk beleid",data:"online stemmen veel deelnemers trok, maar vooral jongeren bereikte die al politiek geïnteresseerd waren",stake:"jongeren, scholen, gemeenteraad en buurtorganisaties",bias:"een hoge opkomst werd verward met een representatieve uitslag",decision:"online stemmen te combineren met gelote panels en schoolgesprekken",concept:"representativiteit"},
 {domain:"persoonlijke financiën",setting:"een ondernemerschapswedstrijd",issue:"hoe winst, groei en maatschappelijke waarde moesten worden verdeeld",data:"een goedkoop product snel winst gaf, terwijl een duurzamer ontwerp later lagere kosten en sterkere klantloyaliteit kon opleveren",stake:"oprichters, klanten, investeerders en producenten",bias:"de jury alleen het eerste verkoopjaar vergeleek",decision:"een meerjarenbegroting met verschillende scenario’s te maken",concept:"scenarioanalyse"}
];
const zanaRoles=["projectleider","kritische verslaggever","teamcaptain","junior-bestuurder","onderzoeker","onderhandelaar"];
const zanaComplications=["halverwege een nieuwe dataset verscheen","een belangrijke bron zijn eerdere uitspraak corrigeerde","de groep sterk verdeeld raakte","een deadline onverwacht werd vervroegd","een journalist een te eenvoudige conclusie publiceerde","een belanghebbende niet aan het eerste overleg had deelgenomen"];
const zanaOpeners=["Zana had geleerd dat een overtuigend antwoord niet automatisch een goed antwoord is.","De vergadering begon met een eenvoudige vraag die al snel ingewikkelder bleek.","Op papier leek de keuze overzichtelijk; in werkelijkheid botsten verschillende waarden.","Zana was niet de oudste deelnemer, maar wel degene die als eerste vroeg hoe de cijfers waren verzameld.","Iedereen wilde snel beslissen, terwijl Zana juist wilde weten welke aannames onder het voorstel lagen."];
function zanaStory(seed,level=5){
 const r=rng(hash("zana"+seed)),d=pick(r,zanaDomains),role=pick(r,zanaRoles),comp=pick(r,zanaComplications),open=pick(r,zanaOpeners);
 const storyCode=hash(seed).toString(36).toUpperCase();
 const title=`Zana en het dilemma van ${d.domain}`;
 const paras=[
 `${open} Het projectdossier droeg code ${storyCode}. Als ${role} werkte ze in ${d.setting} aan een vraagstuk: ${d.issue}. Het onderwerp paste bij haar ambitie om later leiding te geven, maar ze wist dat leiderschap niet betekent dat je als eerste het hardst praat. Het betekent dat je de juiste vragen stelt, belangen onderscheidt en verantwoordelijkheid neemt voor gevolgen die pas later zichtbaar worden.`,
 `De eerste presentatie leek duidelijk. Uit de cijfers bleek dat ${d.data}. Een deel van de groep wilde daarom onmiddellijk kiezen. Zana noteerde echter niet alleen de uitkomst, maar ook de gebruikte periode, de omvang van de onderzoeksgroep en wat buiten de meting was gebleven. Zij vroeg: “Wanneer noemen wij dit succes, voor wie, en over welke termijn?”`,
 `Die vraag veranderde het gesprek. De belangrijkste betrokkenen waren ${d.stake}. Hun belangen overlapten deels, maar niet volledig. Een oplossing kon financieel aantrekkelijk zijn en tegelijk extra risico of ongelijkheid veroorzaken. Zana maakte daarom een tabel met vier kolommen: voordeel, nadeel, onzekerheid en omkeerbaarheid. Een besluit dat later gemakkelijk kon worden aangepast, mocht volgens haar met iets meer onzekerheid worden getest dan een onomkeerbare keuze.`,
 `Vervolgens ontdekte ze een vertekening: ${d.bias}. Dat betekende niet automatisch dat de gepresenteerde informatie onwaar was. Wel betekende het dat de selectie van feiten de lezer in één richting kon duwen. Zana zocht de oorspronkelijke bron, controleerde definities en vergeleek de cijfers met een onafhankelijke publicatie.`,
 `Toen ${comp}, moest de groep opnieuw bepalen welke informatie zwaar woog. Sommige deelnemers vonden dat twijfel vooral vertraging veroorzaakte. Zana antwoordde dat zorgvuldig denken iets anders is dan eindeloos uitstellen. Zij stelde een beslisgrens voor: welke feiten moesten zeker zijn, welke onzekerheden konden worden gevolgd en bij welk signaal zou het besluit opnieuw worden bekeken?`,
 `Voordat de groep koos, formuleerde Zana bewust het sterkste tegenargument tegen haar eigen voorkeur. Dat vond ze ongemakkelijk, maar juist nuttig. Een plan wordt niet sterker doordat je kritiek ontwijkt; het wordt sterker wanneer je laat zien welke kritiek terecht is en welke aanvullende waarborgen nodig zijn. De groep onderzocht daarom ook een alternatief scenario waarin de omstandigheden ongunstiger uitpakten dan verwacht.`,
 `Ze bespraken vervolgens wie de kosten zou dragen wanneer het plan mislukte en wie het meeste voordeel kreeg wanneer het wel lukte. Die verdelingsvraag bleek minstens zo belangrijk als het gemiddelde resultaat. Een positieve totaalscore kon namelijk verbergen dat één groep vrijwel alle nadelen droeg. Zana stelde daarom voor om niet alleen gemiddelden, maar ook verschillen tussen groepen te rapporteren.`,
 `Op basis daarvan koos de groep ervoor ${d.decision}. De keuze was minder spectaculair dan het eerste voorstel, maar beter uitlegbaar. Bovendien bevatte het besluit vaste evaluatiemomenten. Zo kon de groep leren van de werkelijkheid in plaats van te doen alsof alle gevolgen vooraf bekend waren.`,
 `Na afloop schreef Zana in haar notitieboek dat het kernbegrip van deze opdracht “${d.concept}” was. Ze begreep dat volwassen keuzes zelden bestaan uit een simpele tegenstelling tussen goed en fout. Vaak gaat het om de kwaliteit van criteria, de betrouwbaarheid van informatie, de verdeling van voor- en nadelen en de bereidheid om een besluit bij te stellen zonder je oorspronkelijke doel te vergeten.`,
 `Thuis vroeg Dani of dit betekende dat je bij een penalty ook eerst een tabel moest maken. Zana lachte. “Nee, daar heb je soms maar één seconde. Maar juist daarom train je vooraf hoe je kijkt.” Lena stelde voor om alle moeilijke vergaderingen op te lossen met roze stickers. Zana vond dat eerlijk gezegd geen slecht idee: zelfs een serieus proces mocht overzichtelijk en menselijk blijven.`
 ];
 const qs=[
  mc("Welk centraal vraagstuk onderzoekt de tekst?",d.issue,zanaDomains.filter(x=>x.issue!==d.issue).slice(0,3).map(x=>x.issue),"Het vraagstuk wordt in de eerste alinea expliciet geïntroduceerd.","hoofdzaak"),
  mc("Waarom noteert Zana ook periode, onderzoeksgroep en ontbrekende informatie?","Om te beoordelen hoe sterk en algemeen geldig de conclusie is.",["Om de presentatie langer te maken.","Omdat cijfers zonder context altijd verboden zijn.","Om de betrokkenen te overtuigen zonder discussie."],"De kwaliteit van een conclusie hangt mede af van methode, context en beperkingen.","kritisch lezen"),
  mc("Welke vertekening wordt in de tekst genoemd?",d.bias,zanaDomains.filter(x=>x.bias!==d.bias).slice(0,3).map(x=>x.bias),"De tekst maakt onderscheid tussen onjuiste informatie en selectief gepresenteerde informatie.","bron"),
  mc("Wat is de functie van de tabel met voordeel, nadeel, onzekerheid en omkeerbaarheid?","De verschillende gevolgen en risico’s systematisch vergelijken.",["Eén belanghebbende automatisch gelijk geven.","Alle onzekerheid uit het besluit verwijderen.","Alleen financiële gevolgen berekenen."],"De tabel is een afwegingsinstrument, geen automatische uitkomst.","tekstverband"),
  mc("Welke uitspraak past het best bij Zana’s visie op zorgvuldig beslissen?","Je bepaalt vooraf welke onzekerheid acceptabel is en wanneer je opnieuw evalueert.",["Je wacht tot alle onzekerheid verdwenen is.","Je kiest altijd de snelste oplossing.","Je volgt zonder controle de populairste bron."],"De beslisgrens en evaluatiemomenten vormen de kern van haar aanpak.","inference"),
  mc(`Wat betekent “${d.concept}” hier het best?`,zanaConcept(d.concept),["een willekeurige mening zonder criteria","een truc om moeilijke vragen te vermijden","een garantie dat een keuze nooit fout kan gaan"],"De betekenis volgt uit de manier waarop het begrip in de afweging wordt gebruikt.","woordenschat"),
  mc("Welke tekststructuur overheerst?","Vraagstuk – informatie – kritiek – afweging – besluit – reflectie",["Chronologische biografie zonder argumenten","Instructie met alleen losse stappen","Beschrijving van één plaats zonder conclusie"],"De tekst bouwt een beredeneerd besluit op vanuit een dilemma.","structuur"),
  mc("Welke aanvullende bron zou het besluit het meest versterken?","Een onafhankelijke analyse die methode, aannames en verschillende scenario’s laat zien.",["Een korte advertentie van de partij die financieel voordeel heeft.","Een anonieme reactie zonder controleerbare details.","Een populaire video die alleen de conclusie herhaalt."],"Een controleerbare, onafhankelijke bron helpt methode en aannames te toetsen.","brongebruik")
 ];
 return{title,story:paras.join("\n\n"),questions:qs,level,genre:d.domain,estimatedWords:paras.join(" ").split(/\s+/).length,seed};
}
function zanaConcept(c){const d={tijdshorizon:"de periode waarover gevolgen worden beoordeeld",meetbaarheid:"de mate waarin iets betrouwbaar in cijfers of waarnemingen kan worden vastgelegd",proportionaliteit:"of een maatregel niet zwaarder is dan nodig voor het doel",onzekerheid:"wat nog niet voldoende bekend of bewezen is",bronverificatie:"controleren waar informatie vandaan komt en of die klopt",afwegingskader:"vooraf gekozen criteria waarmee opties worden vergeleken",risicobeheersing:"risico’s herkennen, beperken en blijven volgen",systeembenadering:"kijken hoe meerdere onderdelen elkaar beïnvloeden",verantwoordelijkheid:"zelf kunnen uitleggen en dragen waarom een keuze is gemaakt","duurzame prestatie":"goed presteren zonder ontwikkeling en gezondheid op langere termijn te beschadigen",representativiteit:"de mate waarin deelnemers een bredere groep werkelijk weerspiegelen",scenarioanalyse:"meerdere mogelijke toekomsten doorrekenen en vergelijken"};return d[c]||"een precies begrip voor een zorgvuldige keuze"}

const lenaScenes=[
 {title:"Lena en de regenbooghockeybal",place:"het kleine hockeyveld",friend:"een vrolijke egel",goal:"drie gekleurde ballen naar het juiste doel brengen",problem:"de rode bal onder een bankje rolde",solution:"samen bukken en de bal rustig terugrollen",items:["rode bal","gele bal","blauwe bal"],answer:"de rode bal"},
 {title:"Lena en het slapende draakje",place:"een zacht kussenkasteel",friend:"een klein groen draakje",goal:"vier sterren verzamelen zonder het draakje wakker te maken",problem:"één ster achter een rammelende doos lag",solution:"de doos heel langzaam optillen",items:["ster","maan","wolk"],answer:"de ster"},
 {title:"Lena en de dierenparade",place:"het park naast huis",friend:"een dansende pinguïn",goal:"de dieren van klein naar groot laten lopen",problem:"de olifant vooraan wilde staan",solution:"samen tellen en een nieuwe rij maken",items:["muis","hond","olifant"],answer:"de olifant"},
 {title:"Lena’s eerste hockeyles",place:"de sporthal",friend:"een meisje met paarse veters",goal:"de bal vijf keer zacht vooruit tikken",problem:"de bal steeds te ver wegschoot",solution:"kleine tikjes geven en naar de bal blijven kijken",items:["stick","bal","pion"],answer:"de stick"},
 {title:"Lena en de maanvis",place:"een glinsterend zwembad",friend:"een zilveren maanvis",goal:"zes bubbels tellen",problem:"de bubbels snel uit elkaar dreven",solution:"ze één voor één aanwijzen",items:["vis","bubbel","schelp"],answer:"de bubbel"},
 {title:"Lena bouwt een roze raket",place:"de speelkamer",friend:"een robot met wiebelarmen",goal:"een raket van cirkels, vierkanten en driehoeken maken",problem:"de driehoek nergens te vinden was",solution:"onder het blauwe kussen kijken",items:["cirkel","vierkant","driehoek"],answer:"de driehoek"}
];
function lenaStory(seed,level=1){
 const r=rng(hash("lena"+seed)),s=pick(r,lenaScenes),number=2+Math.floor(r()*5),storyCode=hash(seed).toString(36).toUpperCase();
 const weather=pick(r,["De zon maakte gouden vlekjes op de grond.","Buiten tikte zachte regen tegen het raam.","Er waaide een vrolijke wind langs de vlaggetjes.","De lucht was roze en oranje.","Er lagen kleine plassen die glinsterden.","Een wolk leek precies op een konijn."]);
 const extra=pick(r,["Onderweg telde Lena drie vogels.","Lena vond een veertje met twee kleuren.","Een vlinder ging even op haar schoen zitten.","Ze hoorde ergens een grappig piepgeluid.","Op de grond lag een spoor van ronde steentjes.","Een klein belletje rinkelde precies vier keer."]);
 const ending=pick(r,["Daarna koos ze een roze sticker voor haar avonturenboek.","Ze maakte een tekening met een hele grote zon.","Ze gaf iedereen een zachte high five.","Ze zong een zelfbedacht overwinningsliedje.","Ze bouwde thuis het avontuur na met blokken.","Ze vertelde het verhaal nog een keer aan haar knuffel."]);
 const story=`${weather} Op haar avonturenkaart stond regenboogcode ${storyCode}. Lena ging naar ${s.place}. Daar zag ze ${s.friend}. “Kom je helpen?” vroeg haar nieuwe vriend. Samen wilden ze ${s.goal}. ${extra}

Eerst ging het goed. Lena keek, wees en telde rustig. Toen ontstond er een probleem: ${s.problem}. Lena stopte even. Ze dacht na en zei: “Ik probeer het nog een keer, maar nu langzaam.”

De oplossing was eenvoudig: ${s.solution}. Het lukte! Lena klapte ${number} keer in haar handen. Daarna deden ze een vrolijk dansje. “Kleine stapjes zijn ook echte stappen,” zei Lena.

Thuis vertelde ze Dani en Zana alles. Dani maakte er een stoer avontuur van en Zana tekende een mooie kaart. Lena koos zelf de kleuren. ${ending}`;
 return{title:s.title,story,questions:[mc("Waar was Lena?",s.place,lenaScenes.filter(x=>x.place!==s.place).slice(0,3).map(x=>x.place),"Dat hoor je aan het begin van het verhaal.","luisteren"),mc("Wat hielp Lena om het probleem op te lossen?",s.solution,lenaScenes.filter(x=>x.solution!==s.solution).slice(0,3).map(x=>x.solution),"Lena deed dit rustig en toen lukte het.","begrip"),mc(`Welk ding hoort bij dit verhaal?`,s.answer,s.items.filter(x=>x!==s.answer).concat(["trein"]),"Dit voorwerp speelt een duidelijke rol in het verhaal.","herkennen")],level,genre:"kleuteravontuur",estimatedWords:story.split(/\s+/).length,seed};
}

const spellingDani=[
 ["Tijdens de finale ___ Dani de bal rustig aan.","neemt",["neemd","neemt","neemtj"],"Bij hij/Dani krijgt de stam neem een t: neemt."],
 ["De keeper maakt een geweldige ___.","redding",["reding","redding","retting"],"Redding schrijf je met dubbel d."],
 ["Na de training drinken de spelers uit hun ___.","bidons",["bidon's","bidons","biedons"],"Het gewone meervoud is bidons, zonder apostrof."],
 ["Dani ziet een ___ auto langs het veld.","glanzende",["glansende","glanzende","glansende"],"Glanzende komt van glanzen en schrijf je met z."],
 ["De coach legt de ___ nog één keer uit.","strategie",["strateegie","strategie","strattegie"],"Strategie schrijf je met één t en ie aan het einde."],
 ["Het team speelt een spannende ___.","wedstrijd",["wedstrijt","wedstrijd","wedstrijt"],"Wedstrijd eindigt op d, ook al hoor je vaak een t."],
 ["De spelers rennen ___ naar de middenlijn.","onmiddellijk",["onmiddelijk","onmidellijk","onmiddellijk"],"Onmiddellijk heeft dubbel d en dubbel l."],
 ["De bal rolt tussen twee ___ door.","pionnen",["pionen","pionnen","pioonen"],"Na een korte klank verdubbelt de medeklinker: pionnen."],
 ["Dani heeft zijn schoenen zelf ___.","gestrikt",["gestrickd","gestrikt","gestrickdt"],"Het voltooid deelwoord is gestrikt."],
 ["De trainer zegt: ‘___ eerst en schiet daarna.’","Kijk",["Kijk","Kijkt","Kyk"],"Bij een opdracht gebruik je de stam: kijk."],
 ["De uitvinder test een nieuw ___.","prototype",["prototypen","prototype","prototiepe"],"Prototype eindigt op -type."],
 ["Na het doelpunt juichen de ___.","supporters",["suporters","supporters","supporter's"],"Supporters heeft dubbel p en geen apostrof."],
 ["De scheidsrechter ___ voor een overtreding.","fluit",["fluyt","fluit","fluid"],"Fluit schrijf je met ui en eindigt op t."],
 ["Dani bleef rustig, ___ het publiek hard riep.","hoewel",["hoewel","hoe wel","houweel"],"Hoewel is één woord."],
 ["De bal vloog over de ___.","zijlijn",["zeilijn","zijlijn","zylijn"],"Zijlijn schrijf je met ij en als samenstelling aan elkaar."],
 ["Welke zin is juist?","Dani zei: ‘Ik blijf kijken.’",["Dani zei ‘Ik blijf kijken’.","Dani zei: ‘Ik blijf kijken.’","Dani, zei: ‘ik blijf kijken.’"],"Na zei komt een dubbele punt; de gesproken zin krijgt hoofdletter en punt."],
 ["De spelers hebben hard ___.","getraind",["getraint","getraind","getraindt"],"Getraind eindigt op d."],
 ["De snelle spits ___ gisteren twee keer.","scoorde",["scoorde","scoorten","scoortte"],"De verleden tijd van scoren is scoorde."],
 ["Het publiek wordt steeds ___.","enthousiaster",["entousiaster","enthousiaster","enthousjaster"],"Enthousiast begint met enth- en heeft ou."],
 ["De verdediger probeert Dani te ___.","misleiden",["misleijden","misleiden","mislijden"],"Misleiden schrijf je met ei."]
];
const spellingZana=[
 ["De directie heeft de resultaten zorgvuldig ___.","geanalyseerd",["geanalyseert","geanalyseerd","geanaliseerd"],"Het voltooid deelwoord is geanalyseerd; het werkwoord is analyseren."],
 ["Gisteren ___ Zana de vergadering.","leidde",["leide","leidde","lijdde"],"De verleden tijd van leiden is leidde."],
 ["De commissie ___ volgende week een besluit.","neemt",["neemd","neemt","neemdt"],"Bij commissie (zij) schrijf je stam + t: neemt."],
 ["Welke zin is correct?","Hoewel het voorstel ambitieus was, bleef de onderbouwing onvolledig.",["Hoewel het voorstel ambitieus was bleef, de onderbouwing onvolledig.","Hoewel het voorstel ambitieus was, bleef de onderbouwing onvolledig.","Hoewel, het voorstel ambitieus was bleef de onderbouwing onvolledig."],"Na een bijzin vooraan volgt een komma."],
 ["De onderzoekers presenteren verschillende ___.","scenario’s",["scenario's","scenario’s","scenarios"],"Bij dit meervoud voorkomt de apostrof een verkeerde uitspraak."],
 ["De nieuwe gegevens ___ de eerdere conclusie.","weerleggen",["weerleggen","weerlegen","weêrleggen"],"Weerleggen heeft dubbel g."],
 ["De argumenten zijn niet alleen overtuigend, maar ook ___.","controleerbaar",["controlleerbaar","controleerbaar","kontroleerbaar"],"Controleerbaar komt van controleren."],
 ["Welke zin gebruikt het verwijswoord correct?","Het bedrijf veranderde zijn strategie omdat die niet meer werkte.",["Het bedrijf veranderde haar strategie omdat hij niet meer werkte.","Het bedrijf veranderde zijn strategie omdat die niet meer werkte.","Het bedrijf veranderde hun strategie omdat deze niet meer werkte."],"Bedrijf is onzijdig; strategie is een de-woord."],
 ["De voorzitter vroeg of iedereen het voorstel had ___.","begrepen",["begrijpt","begrepen","begrijpen"],"Na had staat het voltooid deelwoord: begrepen."],
 ["De gevolgen waren groter dan vooraf ___.","verwacht",["verwachd","verwacht","verwagdt"],"Verwacht eindigt op t volgens ’t kofschip."],
 ["Welke zin is het meest precies?","De steekproef was te klein om de uitkomst te veralgemenen.",["De proef was gewoon een beetje klein.","De steekproef was te klein om de uitkomst te veralgemenen.","De cijfers waren klein dus alles klopte niet."],"Deze zin benoemt precies wat de beperking is."],
 ["De universiteit publiceerde haar financiële ___.","prognose",["prognoze","prognose","prochnoze"],"Prognose schrijf je met g en s."],
 ["De besluiten worden jaarlijks ___.","geëvalueerd",["geevalueerd","geëvalueerd","geëvaluteerd"],"De trema laat zien dat ge-e apart wordt uitgesproken."],
 ["De journalist controleerde zowel de bron ___ de datum.","als",["dan","als","ofwel"],"De vaste combinatie is zowel ... als."],
 ["Het plan is duur; ___ kan het op lange termijn geld besparen.","desondanks",["daarom","desondanks","omdat"],"Desondanks drukt een tegenstelling uit."],
 ["Welke zin is correct?","De ideeën van de leerlingen zijn goed onderbouwd.",["De ideëen van de leerlingen zijn goed onderbouwt.","De ideeën van de leerlingen zijn goed onderbouwd.","De ideeën van de leerling’en zijn goed onderbouwd."],"Ideeën krijgt een trema; onderbouwd eindigt op d."],
 ["Zana vroeg zich af ___ de ranglijst werkelijk mat.","wat",["dat","wat","als"],"Na ‘zich afvragen’ past hier het vraagwoord wat."],
 ["De raad wil het voorstel niet afwijzen, maar eerst ___.","herzien",["herzienen","herzien","herziet"],"Na wil staat het hele werkwoord: herzien."],
 ["Het onderzoek is onafhankelijk ___.","uitgevoerd",["uitgevoert","uitgevoerd","uit gevoerd"],"Uitgevoerd is één woord en eindigt op d."],
 ["De conclusie klinkt overtuigend; zij is echter onvoldoende ___.","onderbouwd",["onderbouwt","onderbouwd","onder baut"],"Na is staat een bijvoeglijk gebruikt voltooid deelwoord: onderbouwd."]
];
const spellingLena=[
 ["Welk woord begint met de letter B?","bal",["bal","vis","maan"],"Bal begint met b."],
 ["Welk woord rijmt op kat?","mat",["mat","boom","vis"],"Kat en mat klinken aan het einde hetzelfde."],
 ["Welke letter hoor je vooraan in zon?","z",["z","m","p"],"Zon begint met de klank z."],
 ["Welk woord is langer?","olifant",["olifant","kat","bal"],"Olifant heeft de meeste klanken en letters."],
 ["Welk plaatje begint met de klank h?","hond",["hond","muis","roos"],"Hond begint met h."],
 ["Maak het woord: v - i - s","vis",["vis","vos","vas"],"De klanken v-i-s vormen vis."],
 ["Welk woord hoort bij 🏑?","hockeystick",["hockeystick","banaan","kussen"],"Met een hockeystick speel je hockey."],
 ["Welk woord rijmt op maan?","haan",["haan","muis","boot"],"Maan en haan eindigen met dezelfde klank."],
 ["Welke letter komt na A?","B",["B","D","Z"],"Na A komt B."],
 ["Welk woord begint hetzelfde als Lena?","leeuw",["leeuw","pop","vis"],"Lena en leeuw beginnen met l."],
 ["Welk woord heeft twee stukjes: voet-bal?","voetbal",["voetbal","vis","maan"],"Voetbal kun je klappen als voet-bal."],
 ["Welke letter hoort bij deze klank: mmm?","m",["m","s","k"],"De klank mmm hoort bij m."]
];
function makeSpelling(profile,seed,count=12){const bank=profile==="dani"?spellingDani:profile==="zana"?spellingZana:spellingLena;const r=rng(hash(profile+seed+"spell"));let chosen=shuffle(r,bank);while(chosen.length<count)chosen=chosen.concat(shuffle(r,bank));return chosen.slice(0,count).map((x,i)=>({id:i,prompt:x[0],answer:x[1],options:shuffle(r,x[2]),explain:x[3],mode:i%4===1?"sentence":i%4===2?"rule":"choice"}));}

function mathQuestion(profile,level,r,i){
 const c=(prompt,answer,explain,options=null,kind="rekenen")=>({prompt,answer:String(answer).replace(".",","),explain,options:options?shuffle(r,options.map(String)):null,kind});
 if(profile==="lena"){
  const mode=i%6;if(mode===0){const n=2+Math.floor(r()*9);return c(`Hoeveel sterren zie je? ${"⭐".repeat(n)}`,n,"Tel één voor één en wijs mee.")}
  if(mode===1){const a=Math.floor(r()*6),b=Math.floor(r()*(6-a));return c(`${a} + ${b} = ?`,a+b,"Je mag de getallen met vingers of blokjes maken.")}
  if(mode===2){const a=3+Math.floor(r()*7),b=Math.floor(r()*Math.min(4,a+1));return c(`${a} − ${b} = ?`,a-b,"Begin bij het grootste getal en haal er één voor één af.")}
  if(mode===3){const a=1+Math.floor(r()*9),b=1+Math.floor(r()*9);return c(`Welk getal is groter: ${a} of ${b}?`,Math.max(a,b),"Het grootste getal hoort bij de grootste hoeveelheid.",[a,b])}
  if(mode===4){const seq=[1,2,3,4,5,6,7,8,9];const start=Math.floor(r()*5);return c(`Welk getal komt hierna? ${seq[start]}, ${seq[start+1]}, ${seq[start+2]}, ...`,seq[start+3],"Tel steeds één verder.")}
  return c("Welke vorm heeft geen hoek?","cirkel","Een cirkel is rond en heeft geen hoek.",["cirkel","vierkant","driehoek"]);
 }
 if(profile==="dani"){
  const mode=i%10;
  if(mode===0){const a=100+Math.floor(r()*800),b=20+Math.floor(r()*250);return c(`${a} + ${b} = ?`,a+b,"Tel eerst honderdtallen, daarna tientallen en eenheden.")}
  if(mode===1){const a=350+Math.floor(r()*600),b=40+Math.floor(r()*Math.min(350,a-20));return c(`${a} − ${b} = ?`,a-b,"Trek in handige stappen af en controleer met optellen.")}
  if(mode===2){const a=pick(r,[3,4,6,7,8,9]),b=2+Math.floor(r()*10);return c(`${a} × ${b} = ?`,a*b,`Gebruik de tafel van ${a}.`) }
  if(mode===3){const b=pick(r,[3,4,5,6,8,10]),q=2+Math.floor(r()*10);return c(`${b*q} ÷ ${b} = ?`,q,"Controleer door je antwoord weer te vermenigvuldigen.")}
  if(mode===4){const euro=pick(r,[20,25,30,50]),price=pick(r,[7.5,12.75,18.4,23.9]);const ans=(euro-price).toFixed(2);return c(`Je betaalt € ${euro.toFixed(2).replace(".",",")} voor iets van € ${price.toFixed(2).replace(".",",")}. Hoeveel krijg je terug?`,ans,"Trek de prijs af van het betaalde bedrag.")}
  if(mode===5){const h=pick(r,[14,15,16,17]),m=pick(r,[10,20,25,35,40]);const add=pick(r,[20,30,45,60]);let total=h*60+m+add;return c(`De training start om ${h}:${String(m).padStart(2,"0")} en duurt ${add} minuten. Hoe laat is hij klaar?`,`${Math.floor(total/60)}:${String(total%60).padStart(2,"0")}`,"Tel de minuten op; maak bij 60 minuten een nieuw uur.")}
  if(mode===6){const total=pick(r,[24,32,36,40,48]),den=pick(r,[2,3,4,6,8]);const valid=total%den===0?den:4;return c(`Wat is 1/${valid} van ${total}?`,total/valid,`Deel ${total} door ${valid}.`) }
  if(mode===7){const cm=pick(r,[125,230,345,480]);return c(`${cm} cm = hoeveel meter en centimeter?`,`${Math.floor(cm/100)} m ${cm%100} cm`,"100 centimeter is 1 meter.")}
  if(mode===8){const seats=pick(r,[6,8,9]),rows=pick(r,[4,5,7]);return c(`In een kleine tribune zijn ${rows} rijen met ${seats} stoelen. Hoeveel stoelen zijn er?`,rows*seats,"Aantal rijen × stoelen per rij.")}
  const start=2+Math.floor(r()*8),step=2+Math.floor(r()*8);return c(`Welk getal volgt? ${start}, ${start+step}, ${start+2*step}, ${start+3*step}, ...`,start+4*step,`Er komt steeds ${step} bij.`);
 }
 const mode=i%12;
 if(mode===0){const base=pick(r,[80,120,160,240,360]),pct=pick(r,[10,15,20,25,30,40]);return c(`Hoeveel is ${pct}% van ${base}?`,base*pct/100,"Bereken eerst 10% of gebruik een breuk.")}
 if(mode===1){const old=pick(r,[60,80,120,150,240]),pct=pick(r,[15,20,25,30]);return c(`Een product van € ${old.toFixed(2).replace(".",",")} krijgt ${pct}% korting. Wat is de nieuwe prijs?`,(old*(1-pct/100)).toFixed(2),"Bereken de korting en trek die af.")}
 if(mode===2){const den=pick(r,[4,5,8,10]),num=1+Math.floor(r()*(den-1)),total=den*pick(r,[6,8,12,15]);return c(`Bereken ${num}/${den} van ${total}.`,num*total/den,"Deel door de noemer en vermenigvuldig met de teller.")}
 if(mode===3){const a=pick(r,[1.25,2.4,3.75,6.8]),b=pick(r,[0.6,1.35,2.25,4.4]);return c(`${String(a).replace(".",",")} + ${String(b).replace(".",",")} = ?`,(a+b).toFixed(2),"Zet de komma’s onder elkaar.")}
 if(mode===4){const ratio=pick(r,[[2,3],[3,5],[4,7]]),factor=pick(r,[4,6,8]);return c(`De verhouding blauw : roze is ${ratio[0]} : ${ratio[1]}. Er zijn ${ratio[0]*factor} blauwe. Hoeveel roze zijn er?`,ratio[1]*factor,"Bepaal eerst met welke factor de verhouding is vermenigvuldigd.")}
 if(mode===5){const a=3+Math.floor(r()*9),b=a+5+Math.floor(r()*14);return c(`Los op: x + ${a} = ${b}.`,b-a,"Trek aan beide kanten hetzelfde getal af.")}
 if(mode===6){const l=pick(r,[6,8,12,15]),w=pick(r,[4,5,7,9]);return c(`Een rechthoek is ${l} cm lang en ${w} cm breed. Wat is de oppervlakte?`,l*w,"Oppervlakte = lengte × breedte.")}
 if(mode===7){const distance=pick(r,[60,90,120,150]),time=pick(r,[2,3,5]);const d=distance-(distance%time);return c(`Een trein rijdt ${d} km in ${time} uur. Wat is de gemiddelde snelheid?`,d/time,"Gemiddelde snelheid = afstand ÷ tijd.")}
 if(mode===8){const data=shuffle(r,[6,7,8,9,10]).slice(0,4);const sum=data.reduce((a,b)=>a+b,0);const fixed=sum%4===0?data:[6,8,10,12];return c(`Wat is het gemiddelde van ${fixed.join(", ")}?`,fixed.reduce((a,b)=>a+b,0)/4,"Tel alles op en deel door het aantal getallen.")}
 if(mode===9){const scale=pick(r,[100,200,500]),cm=pick(r,[3,4,6,8]);return c(`Op een kaart met schaal 1:${scale} is een afstand ${cm} cm. Hoeveel meter is dat echt?`,cm*scale/100,"Vermenigvuldig met de schaal en zet centimeters om in meters.")}
 if(mode===10){const start=pick(r,[120,250,400]),growth=pick(r,[5,10,20]);return c(`Een bedrag van € ${start} groeit één jaar met ${growth}%. Hoeveel is het daarna?`,(start*(1+growth/100)).toFixed(2),"Tel de procentuele groei bij het beginbedrag op.")}
 const n=pick(r,[3,4,5,6]);return c(`Welke uitkomst is gelijk aan ${n}²?`,n*n,"Een kwadraat is het getal maal zichzelf.",[n*2,n*n,n+n+1,n*n+1]);
}
function makeMath(profile,seed,count=20,level=3){const r=rng(hash(profile+seed+"math"));return Array.from({length:count},(_,i)=>mathQuestion(profile,level,r,i));}

const generalBanks={
 english:[
 ["Choose the best sentence.","She has played hockey since she was six.",["She plays hockey since she was six.","She has played hockey since she was six.","She played hockey since six years."],"Use the present perfect for something that started in the past and continues now."],
 ["Which connector shows contrast?","however",["however","therefore","because"],"However introduces a contrast."],
 ["What does ‘reliable source’ mean?","A source that can be checked and is likely to be accurate.",["A source with the brightest colours.","A source that agrees with you.","A source that can be checked and is likely to be accurate."],"Reliable information is transparent and verifiable."],
 ["Choose the most formal sentence.","I would appreciate further information about the programme.",["Tell me more.","I would appreciate further information about the programme.","What’s up with this course?"],"The chosen sentence is precise and suitable for a formal email."],
 ["Complete: If Zana studies in London, she ___ meet students from many countries.","will",["will","would have","has"],"The first conditional uses if + present, will + verb."],
 ["Which word is closest to ‘ambitious’?","determined to achieve something difficult",["afraid to try","determined to achieve something difficult","uninterested in progress"],"Ambitious describes a strong desire to achieve."]
 ],
 world:[
 ["Waarom ontstonden veel steden aan rivieren?","Rivieren boden water, vervoer en handel.",["Rivieren maakten elk land warmer.","Rivieren boden water, vervoer en handel.","Alle rivieren lagen naast hoofdsteden."],"Rivieren waren belangrijk voor bereikbaarheid en economie."],
 ["Wat is het verschil tussen weer en klimaat?","Weer is kortdurend; klimaat beschrijft langjarige patronen.",["Er is geen verschil.","Weer is kortdurend; klimaat beschrijft langjarige patronen.","Klimaat verandert ieder uur."],"Klimaat gaat over gemiddelden en patronen over lange tijd."],
 ["Welke macht maakt in Nederland wetten samen met de regering?","De Staten-Generaal",["De rechterlijke macht","De Staten-Generaal","De Europese Centrale Bank"],"De Eerste en Tweede Kamer vormen samen de Staten-Generaal."],
 ["Waarom was de boekdrukkunst belangrijk?","Kennis kon sneller en goedkoper worden verspreid.",["Boeken werden verboden.","Kennis kon sneller en goedkoper worden verspreid.","Mensen hoefden niet meer te leren lezen."],"Drukwerk vergrootte de verspreiding van ideeën."],
 ["Wat betekent verstedelijking?","Dat een groter deel van de bevolking in steden gaat wonen.",["Dat steden verdwijnen.","Dat landbouw overal stopt.","Dat een groter deel van de bevolking in steden gaat wonen."],"Verstedelijking is groei van het stedelijke aandeel."],
 ["Welke maatregel is vooral klimaatadaptatie?","Hogere dijken en meer wateropvang",["Minder fossiele brandstoffen gebruiken","Hogere dijken en meer wateropvang","Zonnepanelen produceren"],"Adaptatie vermindert gevolgen; mitigatie pakt oorzaken aan."]
 ],
 science:[
 ["Waarom valt een bal weer naar beneden?","Door de zwaartekracht.",["Door geluidsgolven.","Door de zwaartekracht.","Omdat lucht altijd naar boven duwt."],"Zwaartekracht trekt massa’s naar elkaar toe."],
 ["Wat is een eerlijke proef?","Je verandert één factor en houdt andere omstandigheden gelijk.",["Je verandert alles tegelijk.","Je kiest alleen uitkomsten die je verwacht.","Je verandert één factor en houdt andere omstandigheden gelijk."],"Zo kun je het effect van die ene factor beter onderzoeken."],
 ["Waarom is een grotere steekproef vaak nuttig?","Toeval heeft gemiddeld minder invloed op de uitkomst.",["Iedere meting wordt automatisch perfect.","Toeval heeft gemiddeld minder invloed op de uitkomst.","Er zijn dan geen meetfouten meer."],"Een grotere steekproef vermindert vaak toevallige uitschieters."],
 ["Welke energieomzetting gebeurt in een zonnepaneel?","Lichtenergie wordt elektrische energie.",["Warmte wordt zwaartekracht.","Lichtenergie wordt elektrische energie.","Elektriciteit wordt zonlicht."],"Zonnecellen zetten licht om in elektriciteit."],
 ["Waarom blijft een hypothese voorlopig?","Nieuwe waarnemingen kunnen haar ondersteunen of weerleggen.",["Een hypothese is altijd een gok zonder onderzoek.","Nieuwe waarnemingen kunnen haar ondersteunen of weerleggen.","Een hypothese mag nooit worden aangepast."],"Wetenschappelijke verklaringen blijven toetsbaar."],
 ["Wat doet een controlegroep?","Zij biedt een vergelijking zonder de onderzochte behandeling.",["Zij krijgt altijd de hoogste dosis.","Zij biedt een vergelijking zonder de onderzochte behandeling.","Zij bepaalt vooraf de conclusie."],"De vergelijking helpt het effect van de behandeling te isoleren."]
 ],
 critical:[
 ["Een bericht heeft 100.000 likes. Wat kun je daaruit zeker concluderen?","Dat het bericht veel interactie kreeg, niet dat het waar is.",["Dat het bericht waar is.","Dat het bericht wetenschappelijk bewezen is.","Dat het bericht veel interactie kreeg, niet dat het waar is."],"Populariteit en betrouwbaarheid zijn verschillende eigenschappen."],
 ["Welke bron is het sterkst voor een medische claim?","Een systematische analyse van meerdere gecontroleerde onderzoeken.",["Een advertentie van de verkoper.","Een anonieme reactie.","Een systematische analyse van meerdere gecontroleerde onderzoeken."],"Meerdere goed uitgevoerde onderzoeken bieden doorgaans sterkere onderbouwing."],
 ["Wat is een drogreden op de persoon?","De persoon aanvallen in plaats van het argument.",["Een argument met cijfers gebruiken.","De persoon aanvallen in plaats van het argument.","Een bron controleren."],"De inhoud van het argument wordt dan niet behandeld."],
 ["Waarom moet je onderscheid maken tussen correlatie en oorzaak?","Twee dingen kunnen samen veranderen zonder dat het ene het andere veroorzaakt.",["Correlatie bestaat alleen in sport.","Iedere samenhang is automatisch oorzaak.","Twee dingen kunnen samen veranderen zonder dat het ene het andere veroorzaakt."],"Een derde factor of toeval kan de samenhang verklaren."],
 ["Welke vraag helpt bij een grafiek?","Zijn assen, periode en schaal eerlijk weergegeven?",["Heeft de grafiek mooie kleuren?","Zijn assen, periode en schaal eerlijk weergegeven?","Is de titel kort genoeg?"],"Schaal en selectie kunnen de indruk sterk beïnvloeden."],
 ["Wat is een tegenargument?","Een reden die tegen een standpunt of redenering ingaat.",["Een herhaling van hetzelfde standpunt.","Een reden die tegen een standpunt of redenering ingaat.","Een persoonlijke belediging."],"Een goed betoog bespreekt relevante tegenargumenten."]
 ],
 finance:[
 ["Omzet is € 10.000 en kosten zijn € 7.500. Wat is de winst?","2500",["17500","2500","7500"],"Winst = omzet − kosten."],
 ["Waarom maakt een bedrijf een begroting?","Om inkomsten, uitgaven en mogelijke tekorten vooraf te plannen.",["Om winst te garanderen.","Om inkomsten, uitgaven en mogelijke tekorten vooraf te plannen.","Om geen keuzes meer te hoeven maken."],"Een begroting ondersteunt planning maar voorspelt de toekomst niet perfect."],
 ["Wat is een investering?","Geld of tijd inzetten om later waarde of opbrengst te creëren.",["Alleen geld uitgeven aan snoep.","Geld of tijd inzetten om later waarde of opbrengst te creëren.","Elke rekening die al betaald is."],"Een investering is gericht op toekomstige waarde."],
 ["Waarom is kasgeld iets anders dan winst?","Winst is boekhoudkundig; kasgeld gaat over werkelijk ontvangen en betaald geld.",["Er is nooit verschil.","Winst is boekhoudkundig; kasgeld gaat over werkelijk ontvangen en betaald geld.","Kasgeld telt alleen munten."],"Een winstgevend bedrijf kan toch tijdelijk weinig liquide middelen hebben."],
 ["Wat is diversificatie?","Risico spreiden over verschillende activiteiten of bezittingen.",["Alles in één idee investeren.","Risico spreiden over verschillende activiteiten of bezittingen.","Geen enkel risico nemen."],"Spreiding voorkomt dat één tegenvaller alles bepaalt."],
 ["Een product kost € 20 om te maken en wordt verkocht voor € 32. Wat is de brutomarge per stuk?","12",["52","12","20"],"Verkoopprijs − directe productkosten = € 12."]
 ],
 logic:[
 ["Welke vorm volgt? 🔵 🔺 🔵 🔺 ...","🔵",["🔵","🔺","🟩"],"De vormen wisselen steeds af."],
 ["Alle keepers dragen handschoenen. Sam is keeper. Wat volgt?","Sam draagt handschoenen.",["Sam scoort altijd.","Sam draagt handschoenen.","Iedereen met handschoenen is keeper."],"Dit volgt rechtstreeks uit de twee gegeven zinnen."],
 ["Welk getal past? 2, 5, 8, 11, ...","14",["12","13","14"],"Er komt steeds 3 bij."],
 ["Welke hoort er niet bij? haai, dolfijn, walvis, tijger","tijger",["haai","walvis","tijger"],"De tijger leeft niet in zee."],
 ["Een rode doos staat links van een blauwe. De groene staat rechts van de blauwe. Welke staat in het midden?","de blauwe",["de rode","de blauwe","de groene"],"De volgorde is rood – blauw – groen."],
 ["Dani is ouder dan Lena. Zana is ouder dan Dani. Wie is het oudst?","Zana",["Lena","Dani","Zana"],"Zana is ouder dan Dani, en Dani ouder dan Lena."]
 ]
};
function makeBankQuiz(subject,profile,seed,count=10){const bank=generalBanks[subject]||generalBanks.logic;const r=rng(hash(subject+profile+seed));let arr=shuffle(r,bank);while(arr.length<count)arr=arr.concat(shuffle(r,bank));return arr.slice(0,count).map((x,i)=>({id:i,prompt:x[0],answer:x[1],options:shuffle(r,x[2]),explain:x[3],kind:subject}));}

const shopItems=[
 {id:"skin-light",cat:"skin",name:"Zon",art:"☀️",price:0,value:"#f3c6a2"},{id:"skin-warm",cat:"skin",name:"Warm",art:"🌤️",price:0,value:"#d99b6c"},{id:"skin-deep",cat:"skin",name:"Diep",art:"🌞",price:0,value:"#7b482d"},{id:"hair-brown",cat:"hair",name:"Bruin",art:"🤎",price:0,value:"#50301d"},{id:"hair-black",cat:"hair",name:"Zwart",art:"🖤",price:80,value:"#191919"},{id:"hair-blonde",cat:"hair",name:"Blond",art:"💛",price:110,value:"#e2b94f"},{id:"hair-pink",cat:"hair",name:"Roze",art:"💗",price:220,value:"#ef6aa7"},
 {id:"top-blue",cat:"top",name:"Blauw shirt",art:"👕",price:0,value:"#3179ef"},{id:"top-orange",cat:"top",name:"Oranje tenue",art:"🟧",price:160,value:"#ff7d32"},{id:"top-pink",cat:"top",name:"Roze hoodie",art:"🩷",price:180,value:"#e95c9d"},{id:"top-black",cat:"top",name:"CEO blazer",art:"🕴️",price:320,value:"#151b2d"},{id:"top-space",cat:"top",name:"Ruimtepak",art:"🧑‍🚀",price:500,value:"#e9edf8"},
 {id:"bottom-jeans",cat:"bottom",name:"Jeans",art:"👖",price:0,value:"#233d73"},{id:"bottom-sport",cat:"bottom",name:"Sportbroek",art:"🩳",price:120,value:"#131a2b"},{id:"bottom-purple",cat:"bottom",name:"Paars",art:"🟪",price:170,value:"#7255bd"},
 {id:"acc-glasses",cat:"accessory",name:"Zonnebril",art:"🕶️",price:140,value:"🕶️"},{id:"acc-crown",cat:"accessory",name:"Kroon",art:"👑",price:450,value:"👑"},{id:"acc-headphones",cat:"accessory",name:"Headset",art:"🎧",price:220,value:"🎧"},{id:"acc-cap",cat:"accessory",name:"Sportpet",art:"🧢",price:130,value:"🧢"},{id:"acc-none",cat:"accessory",name:"Geen",art:"➖",price:0,value:""},
 {id:"pet-dog",cat:"pet",name:"Hond",art:"🐶",price:250,value:"🐶"},{id:"pet-dragon",cat:"pet",name:"Draak",art:"🐲",price:600,value:"🐲"},{id:"pet-robot",cat:"pet",name:"Robot",art:"🤖",price:420,value:"🤖"},{id:"pet-shark",cat:"pet",name:"Minihaai",art:"🦈",price:500,value:"🦈"},{id:"pet-none",cat:"pet",name:"Geen",art:"➖",price:0,value:""},
 {id:"emote-goal",cat:"emote",name:"GOAL!",art:"⚽",price:100,value:"⚽"},{id:"emote-star",cat:"emote",name:"Ster",art:"⭐",price:100,value:"⭐"},{id:"emote-heart",cat:"emote",name:"Hart",art:"💖",price:100,value:"💖"},{id:"emote-brain",cat:"emote",name:"Brein",art:"🧠",price:150,value:"🧠"},
 {id:"world-house",cat:"world",name:"Droomhuis",art:"🏡",price:450,value:"🏡"},{id:"world-castle",cat:"world",name:"Kasteel",art:"🏰",price:900,value:"🏰"},{id:"world-stadium",cat:"world",name:"Stadion",art:"🏟️",price:750,value:"🏟️"},{id:"world-treehouse",cat:"world",name:"Boomhut",art:"🛖",price:400,value:"🛖"},{id:"world-lambo",cat:"world",name:"Supersportauto",art:"🏎️",price:800,value:"🏎️"},{id:"world-rocket",cat:"world",name:"Raket",art:"🚀",price:850,value:"🚀"},{id:"world-pool",cat:"world",name:"Zwembad",art:"🏊",price:500,value:"🏊"},{id:"world-shop",cat:"world",name:"Fashion Store",art:"🛍️",price:550,value:"🛍️"},{id:"world-campus",cat:"world",name:"University",art:"🎓",price:700,value:"🎓"},{id:"world-hockey",cat:"world",name:"Hockeyveld",art:"🏑",price:450,value:"🏑"},{id:"world-dino",cat:"world",name:"Dino Park",art:"🦖",price:650,value:"🦖"},{id:"world-beach",cat:"world",name:"Strand",art:"🏖️",price:400,value:"🏖️"},{id:"world-tower",cat:"world",name:"CEO Tower",art:"🏢",price:900,value:"🏢"},{id:"world-play",cat:"world",name:"Speeltuin",art:"🛝",price:260,value:"🛝"},{id:"world-flower",cat:"world",name:"Bloementuin",art:"🌸",price:180,value:"🌸"}
];

window.LEVELUP_CONTENT={PROFILE_META,ACTIVITY_META,hash,rng,pick,shuffle,daniStory,zanaStory,lenaStory,makeSpelling,makeMath,makeBankQuiz,shopItems};
})();
